module.exports = Object.freeze({
    GUI_PORT: 8080,
    WS_PORT: 8081,
    
    MODBUS_BAUD: 19200,
    MODBUS_STOPBIT: 2,
    MODBUS_SERIALNAME: 'FTDI',
    MODBUS_TIMEOUT: 500,
    DRIVE_ID: 1,

    ARDUINO_BAUDRATE: 9600,
    ARDUINO_SERIALNAME: 'FTDI',
})