module.exports = Object.freeze({
    GUI_PORT: 8080,
    WS_PORT: 8081,
    
    MODBUS_BAUD: 19200,
    MODBUS_STOPBIT: 2,
    MODBUS_SERIALNAME: 'FTDI',
    MODBUS_TIMEOUT: 500,
    MODBUS_SEND_INTERVAL: 50,

    STATUS_RETRY_COUNT: 5,

    DRIVE_ID: 1,
    PLC_ID: 2,
})